### PR TITLE
Module to import from JSON APi

### PR DESCRIPTION
**Pull request by EDiLD**
Added a small module to import from an API that serve flat JSONs. Just paste the URL and your good to go.
Have a look at tests for an example API (gapminder data)

### CODE REVIEW

**Comment by pvictor** [comment]
Thanks! That's interesting.

I have a couple of questions:

* Is {httr} really needed ? It adds an extra dependency when {jsonlite} seems sufficient, e.g. ;

```r
jsonlite::fromJSON("https://cdn.jsdelivr.net/gh/timruffles/gapminder-data-json@74aee1c2878e92608a6219c27986e7cd96154482/gapminder.min.json")
# -> GOOD
jsonlite::fromJSON("https://www.google.fr/")
# -> ERROR
```
It is less rigorous regarding what is provided as URL, but wrapping that in `try()` or `tryCatch()` + checking that output is a `data.frame` could do the job

* while we're at it, can we read something else than json?

```r
# JSON
rio::import("https://raw.githubusercontent.com/dreamRs/datamods/master/inst/extdata/mtcars.json")
# CSV
rio::import("https://raw.githubusercontent.com/dreamRs/datamods/master/inst/extdata/mtcars.csv")
```

It will be more the `import_file` module but with an URL as entrypoint.



Victor

**Comment by EDiLD** [comment]
Great suggestions @pvictor! I'll refine it to a more general `import_url` (perhaps similar to a lightweight `import_file`)

**Comment by EDiLD** [comment]
@pvictor I've changed according to a general `import_url_*()`, that supports all (flat) formats of rio. This also drop the `httr` dependency.

Addtionally, I've also extended `insert_error` to display the message from `try()` - which is used across all modules. This give the user a little bit more information on what might be wrong.

**Comment by pvictor** [comment]
That's perfect, thank you!

I just added an option to retrieve the data's name (file name).

Nice addition for `insert_error` !

**Pull request merged**
